import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "  bg-gray-900"}>
        <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-6 text-white">
          {children}
        </main>
      </body>
    </html>
  );
}
